/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package application.form;

import application.entity.Coach;
import application.func.CoachFunc;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Le Van Phong Tu
 */
public class Form3 extends javax.swing.JPanel {

    /**
     * Creates new form Form3
     */
    public Form3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonreset = new application.swing.ButtonForm();
        buttondone = new application.swing.ButtonForm();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        buttonForm3 = new application.swing.ButtonForm();
        buttonForm4 = new application.swing.ButtonForm();
        textpricehlv = new application.swing.TextFielInForm();
        textaddresshlv = new application.swing.TextFielInForm();
        genderboxhlv = new application.swing.Combobox();
        textsdthlv = new application.swing.TextFielInForm();
        textidhlv = new application.swing.TextFielInForm();
        textsalary = new application.swing.TextFielInForm();
        textnamehlv = new application.swing.TextFielInForm();
        textdobhlv = new application.swing.TextFielInForm();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 19)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN HUẤN LUYỆN VIÊN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 32, 842, 55));

        buttonreset.setBackground(new java.awt.Color(203, 102, 0));
        buttonreset.setForeground(new java.awt.Color(255, 255, 255));
        buttonreset.setText("RESET");
        buttonreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonresetActionPerformed(evt);
            }
        });
        jPanel1.add(buttonreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 550, 140, 50));

        buttondone.setBackground(new java.awt.Color(203, 102, 0));
        buttondone.setForeground(new java.awt.Color(255, 255, 255));
        buttondone.setText("DONE");
        buttondone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttondoneActionPerformed(evt);
            }
        });
        jPanel1.add(buttondone, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, 140, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 19)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 51, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("THÔNG TIN HUẤN LUYỆN VIÊN");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 32, 842, 55));

        buttonForm3.setBackground(new java.awt.Color(203, 102, 0));
        buttonForm3.setForeground(new java.awt.Color(255, 255, 255));
        buttonForm3.setText("RESET");
        buttonForm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForm3ActionPerformed(evt);
            }
        });
        jPanel2.add(buttonForm3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 550, 140, 50));

        buttonForm4.setBackground(new java.awt.Color(203, 102, 0));
        buttonForm4.setForeground(new java.awt.Color(255, 255, 255));
        buttonForm4.setText("DONE");
        buttonForm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForm4ActionPerformed(evt);
            }
        });
        jPanel2.add(buttonForm4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, 140, 50));

        textpricehlv.setLabelText("Tiền thuê");
        textpricehlv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textpricehlvActionPerformed(evt);
            }
        });
        jPanel2.add(textpricehlv, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 240, -1));

        textaddresshlv.setLabelText("Địa chỉ");
        textaddresshlv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textaddresshlvActionPerformed(evt);
            }
        });
        jPanel2.add(textaddresshlv, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 240, -1));

        genderboxhlv.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nam", "Nữ", "Khác" }));
        genderboxhlv.setLabeText("Giới tính");
        genderboxhlv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderboxhlvActionPerformed(evt);
            }
        });
        jPanel2.add(genderboxhlv, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 90, 50));

        textsdthlv.setLabelText("Số điện thoại");
        textsdthlv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textsdthlvActionPerformed(evt);
            }
        });
        jPanel2.add(textsdthlv, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 240, -1));

        textidhlv.setLabelText("ID");
        textidhlv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textidhlvActionPerformed(evt);
            }
        });
        jPanel2.add(textidhlv, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 90, -1));

        textsalary.setLabelText("Lương");
        textsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textsalaryActionPerformed(evt);
            }
        });
        jPanel2.add(textsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 240, -1));

        textnamehlv.setLabelText("Họ và tên");
        textnamehlv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnamehlvActionPerformed(evt);
            }
        });
        jPanel2.add(textnamehlv, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 390, -1));

        textdobhlv.setLabelText("Ngày sinh");
        textdobhlv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textdobhlvActionPerformed(evt);
            }
        });
        jPanel2.add(textdobhlv, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 260, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void textdobhlvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textdobhlvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textdobhlvActionPerformed

    private void genderboxhlvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderboxhlvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderboxhlvActionPerformed

    private void textnamehlvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnamehlvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textnamehlvActionPerformed

    private void textidhlvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textidhlvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textidhlvActionPerformed

    private void textsdthlvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textsdthlvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textsdthlvActionPerformed

    private void buttonresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonresetActionPerformed
        // TODO add your handling code here:
        resetField();
        
    }//GEN-LAST:event_buttonresetActionPerformed

    private void buttondoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttondoneActionPerformed

    }//GEN-LAST:event_buttondoneActionPerformed

    private void textaddresshlvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textaddresshlvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textaddresshlvActionPerformed

    private void buttonForm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForm3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonForm3ActionPerformed

    private void buttonForm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForm4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonForm4ActionPerformed

    private void textpricehlvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textpricehlvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textpricehlvActionPerformed

    private void textsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textsalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textsalaryActionPerformed
    
    
    public void setCoachInfo(Coach coach){
        textidhlv.setText(coach.getMaCoach());
        textnamehlv.setText(coach.getName());
        if(coach.getGender().equals("Nam")){
            genderboxhlv.setSelectedIndex(0);
        }
        if(coach.getGender().equals("Nữ")){
            genderboxhlv.setSelectedIndex(1);
        }
        if(coach.getGender().equals("Khác")){
            genderboxhlv.setSelectedIndex(2);
        }
        textdobhlv.setText(coach.getDob());
        textaddresshlv.setText(coach.getAddress());
        textsdthlv.setText(coach.getPhoneNumber());
        textpricehlv.setText(String.valueOf(coach.getRentMoney()));
        textsalary.setText(String.valueOf(coach.getSalary()));
        
    }
    private boolean validateID() {
        
        String id = textidhlv.getText();
        if (id == null || "".equals(id.trim())) {
            textidhlv.requestFocus();
            showMessage("ID không được trống.");
            return false;
        }
        
        return true;
    }
    private boolean validateName() {
        String name = textnamehlv.getText();
        if (name == null || "".equals(name.trim())) {
            textnamehlv.requestFocus();
            showMessage("Tên không được trống");
            return false;
        }
        return true;
    }
    public static boolean isInteger(String str) {
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    private boolean validateGender() {
        int gen = genderboxhlv.getSelectedIndex();
        if (gen==-1) {
            genderboxhlv.requestFocus();
            showMessage("Chưa chọn giới tính");
            return false;
        }
        return true;
    }
    private boolean validateDob() {
        String dob = textdobhlv.getText();
        if (dob == null || "".equals(dob.trim())) {
            textdobhlv.requestFocus();
            showMessage("Tên không được trống");
            return false;
        }
        return true;
    }
    private boolean validateAddress() {
        String address = textaddresshlv.getText();
        if (address == null || "".equals(address.trim())) {
            textaddresshlv.requestFocus();
            showMessage("Địa chỉ không được trống.");
            return false;
        }
        
        return true;
    }
    private boolean validatePhone() {
        String phone = textsdthlv.getText();
        if (phone == null || "".equals(phone.trim())) {
            textsdthlv.requestFocus();
            showMessage("Số điện thoại không được trống.");
            return false;
        }
        return true;
    }
    
    
    
    public Coach getCoachInfo() {
        // validate student
        if (!validateID()|| !validateName()|| !validateGender()|| !validateDob()||!validateAddress()||!validatePhone()) {
            return null;
        }
        try {
            Coach coach = new Coach();
            coach.setMaCoach(textidhlv.getText());
            coach.setName(textnamehlv.getText());
            coach.setGender(genderboxhlv.getItemAt( genderboxhlv.getSelectedIndex()).toString());
            coach.setDob(textdobhlv.getText());
            coach.setAddress(textaddresshlv.getText());
            coach.setPhoneNumber(textsdthlv.getText());
           
            coach.setRentMoney(Integer.parseInt( textpricehlv.getText().trim()));
            coach.setSalary(Integer.parseInt( textsalary.getText().trim()));
            
            return coach;
        } catch (Exception e) {
            showMessage(e.getMessage());
        }
        return null;
    }
     public Coach getCoachInfoFrame() {
        // validate student
        if (!validateID()|| !validateName()|| !validateGender()|| !validateDob()||!validateAddress()||!validatePhone()) {
            return null;
        }
        try {
            Coach coach = new Coach();
            coach.setMaCoach(textidhlv.getText());
            coach.setName(textnamehlv.getText());
            coach.setGender(genderboxhlv.getItemAt( genderboxhlv.getSelectedIndex()).toString());
            coach.setDob(textdobhlv.getText());
            coach.setAddress(textaddresshlv.getText());
            coach.setPhoneNumber(textsdthlv.getText());
           
            coach.setRentMoney(Integer.parseInt( textpricehlv.getText().trim()));
            coach.setSalary(Integer.parseInt( textsalary.getText().trim()));
            
            return coach;
        } catch (Exception e) {
            showMessage(e.getMessage());
        }
        return null;
    }
    public void resetField(){
        CoachFunc func = new CoachFunc();
        
        textidhlv.setText("");
        textnamehlv.setText("");
        genderboxhlv.setSelectedIndex(-1);
        textdobhlv.setText("");
        textsdthlv.setText("");
        textaddresshlv.setText("");
        textpricehlv.setText("");
        textsalary.setText("");
    }
    public void addAddHLVListener(ActionListener listener) {
        System.out.println("do");
        buttondone.addActionListener(listener);
    }
    public void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private application.swing.ButtonForm buttonForm3;
    private application.swing.ButtonForm buttonForm4;
    private application.swing.ButtonForm buttondone;
    private application.swing.ButtonForm buttonreset;
    private application.swing.Combobox genderboxhlv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private application.swing.TextFielInForm textaddresshlv;
    private application.swing.TextFielInForm textdobhlv;
    private application.swing.TextFielInForm textidhlv;
    private application.swing.TextFielInForm textnamehlv;
    private application.swing.TextFielInForm textpricehlv;
    private application.swing.TextFielInForm textsalary;
    private application.swing.TextFielInForm textsdthlv;
    // End of variables declaration//GEN-END:variables
}
