/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package application.form;

import application.entity.Coach;
import application.func.CoachFunc;
import application.func.GymerFunc;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Le Van Phong Tu
 */
public class Form4 extends javax.swing.JPanel {

    /**
     * Creates new form Form4
     */
    public Form4() {
        initComponents();
        CoachFunc func = new CoachFunc();
        TongDoanhThu.setText(func.getCountCoach()+ "\n" +func.tongTienLuongHLV());
        sortList1.addElement("Id");
        sortList1.addElement("Tên");
        sortList1.addElement("Giới tính");
       
        searchbox.setModel(sortList1);
        searchbox.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableColumn1 = new application.swing.TableColumn();
        buttonEdit = new application.swing.ButtonForm();
        buttonReset = new application.swing.ButtonForm();
        buttonDelete = new application.swing.ButtonForm();
        searchbox = new application.swing.Combobox();
        buttonSort = new application.swing.ButtonForm();
        buttontimkiem = new application.swing.ButtonForm();
        textFielInForm1 = new application.swing.TextFielInForm();
        TongDoanhThu = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 19)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BẢNG THÔNG TIN HUẤN LUYỆN VIÊN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 842, 55));

        tableColumn1.setBackground(new java.awt.Color(255, 255, 255));
        tableColumn1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Họ và tên", "Giới tính", "Ngày sinh", "Địa chỉ", "Số điện thoại", "Tiền thuê", "Tiền Lương"
            }
        ));
        jScrollPane1.setViewportView(tableColumn1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 1070, -1));

        buttonEdit.setBackground(new java.awt.Color(203, 102, 0));
        buttonEdit.setForeground(new java.awt.Color(255, 255, 255));
        buttonEdit.setText("Edit");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });
        jPanel1.add(buttonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, 80, 30));

        buttonReset.setBackground(new java.awt.Color(203, 102, 0));
        buttonReset.setForeground(new java.awt.Color(255, 255, 255));
        buttonReset.setText("Reset");
        jPanel1.add(buttonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 130, 80, 30));

        buttonDelete.setBackground(new java.awt.Color(203, 102, 0));
        buttonDelete.setForeground(new java.awt.Color(255, 255, 255));
        buttonDelete.setText("Delete");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(buttonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 130, 80, 30));

        searchbox.setLabeText("");
        jPanel1.add(searchbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 110, -1));

        buttonSort.setBackground(new java.awt.Color(203, 102, 0));
        buttonSort.setForeground(new java.awt.Color(255, 255, 255));
        buttonSort.setText("Sort");
        buttonSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSortActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSort, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 80, 30));

        buttontimkiem.setBackground(new java.awt.Color(203, 102, 0));
        buttontimkiem.setForeground(new java.awt.Color(255, 255, 255));
        buttontimkiem.setText("Search");
        buttontimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttontimkiemActionPerformed(evt);
            }
        });
        jPanel1.add(buttontimkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 80, 30));

        textFielInForm1.setLabelText("Nhập tìm kiếm ở đây");
        textFielInForm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFielInForm1ActionPerformed(evt);
            }
        });
        jPanel1.add(textFielInForm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 180, -1));

        TongDoanhThu.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        TongDoanhThu.setForeground(new java.awt.Color(255, 51, 153));
        TongDoanhThu.setText("jLabel2");
        jPanel1.add(TongDoanhThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(772, -10, 280, 80));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 20, 1151, 631));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSortActionPerformed

    private void buttontimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttontimkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttontimkiemActionPerformed

    private void textFielInForm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFielInForm1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFielInForm1ActionPerformed
    public void addDeleteHLVListener(ActionListener listener) {
        buttonDelete.addActionListener(listener);
    }    
public void addHLVGymerListener(ActionListener listener) {
        buttonDelete.addActionListener(listener);
    }
public void addSortHLVListener(ActionListener listener) {

        buttonSort.addActionListener(listener);
    }
public int getIndexSort(){
        return searchbox.getSelectedIndex();
    }
//    public void addSearchVisitListener(ActionListener listener) {
//
//        txtSearch.addActionListener(listener);
//    }
    public void addEditHLVListener(ActionListener listener) {

        buttonEdit.addActionListener(listener);
    }
    public void addSearchHLVListener(ActionListener listener) {

        buttontimkiem.addActionListener(listener);
    }
    public String timkiemString(){
        if(!textFielInForm1.getText().equals("")||textFielInForm1.getText()!=null){
           
            return textFielInForm1.getText();
            
        }
        else return null;
    }
    public void addResetListener(ActionListener listener){
        buttonReset.addActionListener(listener);
    }
//    public int getIndexSearch(){
//        return boxChoose.getSelectedIndex();
//    }
//    public String getFieldSearch(){
//        return txtSearch.getText();
//    }
    public void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
    }
    public void showCoach(List<Coach> list) {
        int size = list.size();
        // với bảng studentTable có 5 cột, 
        // khởi tạo mảng 2 chiều visits, trong đó:
        // số hàng: là kích thước của list student 
        // số cột: là 5
        Object [][] coaches = new Object[size][8];
        for (int i = 0; i < size; i++) {
            coaches[i][0] = list.get(i).getMaCoach();
            coaches[i][1] = list.get(i).getName();
            //DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
            coaches[i][2] = list.get(i).getGender();
            coaches[i][3] = list.get(i).getDob();
            coaches[i][4] = list.get(i).getAddress();
            coaches[i][5] = list.get(i).getPhoneNumber();
            coaches[i][6] = list.get(i).getRentMoney();
            coaches[i][7] = list.get(i).getSalary();
            
            
        }
        tableColumn1.setModel(new DefaultTableModel(coaches, columnNames));
    }
    
        
    
    public Coach getCoachInfo() {
        // validate student
        int row = tableColumn1.getSelectedRow();

        String Id = tableColumn1.getModel().getValueAt(row,0).toString();
        String name = tableColumn1.getModel().getValueAt(row,1).toString();
        //DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        String gender = tableColumn1.getModel().getValueAt(row,2).toString();
        //LocalDateTime Date = LocalDateTime.parse(DateString,formatter);
        String dob = tableColumn1.getModel().getValueAt(row,3).toString();
        String address = tableColumn1.getModel().getValueAt(row,4).toString();
        String phone = tableColumn1.getModel().getValueAt(row,5).toString();
        int price = Integer.parseInt(tableColumn1.getModel().getValueAt(row,6).toString());
        int salary = Integer.parseInt(tableColumn1.getModel().getValueAt(row,7).toString());
        return new Coach(salary,price,Id, name, gender, address, phone, dob);
    }
    private DefaultComboBoxModel searchList = new DefaultComboBoxModel();
     private DefaultComboBoxModel sortList1 = new DefaultComboBoxModel();
     private DefaultComboBoxModel sortList2 = new DefaultComboBoxModel();
    private final String [] columnNames = new String [] {
            "ID", "Họ và tên", "Giới tính", "Ngày sinh", "Địa chỉ","Số điện thoại","Tiền thuê","Tiền lương"};
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TongDoanhThu;
    private application.swing.ButtonForm buttonDelete;
    private application.swing.ButtonForm buttonEdit;
    private application.swing.ButtonForm buttonReset;
    private application.swing.ButtonForm buttonSort;
    private application.swing.ButtonForm buttontimkiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private application.swing.Combobox searchbox;
    private application.swing.TableColumn tableColumn1;
    private application.swing.TextFielInForm textFielInForm1;
    // End of variables declaration//GEN-END:variables
}
