/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application.form;

import application.entity.Coach;
import java.awt.event.ActionListener;

/**
 *
 * @author Le Van Phong Tu
 */
public class FrameForm4 extends javax.swing.JFrame {

    /**
     * Creates new form FrameForm4
     */
    public FrameForm4(Coach coach) {
        
	initComponents(coach);
	this.coach = coach;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(Coach coach) {

        form32 = new application.form.Form3();
	form32.setCoachInfo(coach);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(form32, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void addListennerEdit(ActionListener listener){

        form32.addAddHLVListener(listener);
    }
    public Coach getCrimeInfo(){
        return form32.getCoachInfo();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private application.form.Form3 form32;
    private Coach coach;
    // End of variables declaration//GEN-END:variables

    	
}
