/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application.form;

import application.entity.Employee;
import java.awt.event.ActionListener;

/**
 *
 * @author Le Van Phong Tu
 */
public class FrameForm6 extends javax.swing.JFrame {

    /**
     * Creates new form FrameForm6
     */
    public FrameForm6(Employee employee) {
        initComponents(employee);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(Employee employee) {
	form52 = new application.form.Form5();
	form52.setEmployeeInfo(employee);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
	getContentPane().add(form52, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));
        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void addListennerEdit(ActionListener listener){

        form52.addAddEmployeeListener(listener);
    }
    public Employee getCrimeInfo(){
        return form52.getEmployeeInfo();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
	private application.form.Form5 form52;
    	private Employee employee;
    // End of variables declaration//GEN-END:variables
}
